# Generated by Django 2.1.15 on 2020-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200917_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
