# Generated by Django 2.1.15 on 2020-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200923_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='tid',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
