# Generated by Django 2.1.15 on 2020-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscribe_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
