# Generated by Django 2.1.15 on 2020-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscribe_is_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_voice',
            field=models.IntegerField(default=1),
        ),
    ]
