# Generated by Django 2.1.15 on 2020-09-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qnareply',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
