# Generated by Django 2.1.15 on 2020-09-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0002_auto_20200921_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='qnareply',
            old_name='date',
            new_name='create_date',
        ),
    ]
