# Generated by Django 2.1.15 on 2020-09-17 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_file', models.FileField(upload_to='')),
                ('caption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.Caption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_voice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('model', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoicePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_purchase', to=settings.AUTH_USER_MODEL)),
                ('voice_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voices.VoiceModel')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('voice_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_rent', to='voices.VoiceModel')),
            ],
        ),
        migrations.AddField(
            model_name='trainvoice',
            name='voice_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voices.VoiceCategory'),
        ),
    ]
