# Generated by Django 2.1.15 on 2020-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicepurchase',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
