# Generated by Django 2.1.15 on 2020-10-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_auto_20200921_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecategory',
            name='is_train',
            field=models.BooleanField(default=False),
        ),
    ]
