# Generated by Django 2.1.15 on 2020-09-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_auto_20200921_1554'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='fairytale',
            name='content',
        ),
        migrations.AddField(
            model_name='voicestorage',
            name='fairytale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Fairytale'),
        ),
        migrations.AddField(
            model_name='voicestorage',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Scenario'),
        ),
        migrations.AddField(
            model_name='voicestorage',
            name='voice_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voices.VoiceModel'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='fairytale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Fairytale'),
        ),
    ]
