# Generated by Django 2.1.15 on 2020-10-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201006_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairytale',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
